// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crapgiujobhigukhhkqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyYXBnaXVqb2JoaWd1a2hoa3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NzMzMzYsImV4cCI6MjA5MTA0OTMzNn0.JJuLk-YA_FxtKZt7zxnEvXG7BUazCsO1icrq3Apwqlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});